
 # DockerHub User & Image name i
 #
 
 name: DockerPushToHub

 env: 
   DOCKER_HUB_IMAGE_NAME: pmm-solana-event-reader 
   DOCKER_HUB_ORGANIZATION: debridgefinance 
   LIMA: lima
   TYROL: tyrol
   PROD: prod

 # Triggers 
 on: 
   push:
     tags:
       - 'v\d+.\d+.\d+' 
  
 jobs:  
 # Push & build 
   docker-build-and-push: 
     runs-on: ubuntu-latest 
     steps: 
       - 
         name: Set up QEMU 
         uses: docker/setup-qemu-action@v2
       - 
         name: Set up Docker Buildx 
         uses: docker/setup-buildx-action@v2 
       - 
         name: Login to DockerHub 
         uses: docker/login-action@v2 
         with: 
           username: ${{ secrets.DOCKER_HUB_USERNAME_TEST }} 
           password: ${{ secrets.DOCKER_HUB_PASSWORD_TEST }} 
       -  
         name: Docker meta 
         id: metadata 
         uses: docker/metadata-action@v4 
         with: 
           images: danielsdv/debridge
           tags: |
             type=raw,value={{tag}}.{{sha}}

       -  
         name: Checkout 
         uses: actions/checkout@v2
       - 
         name: Use ssh agent
         uses: webfactory/ssh-agent@v0.6.0
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

       - 
         name: Build and push LIMA 
         uses: docker/build-push-action@v3 
         with: 
           context: .
           file: Dockerfile
           push: true
           build-args: ENV_VARIABLE=lima
           tags: ${{ steps.metadata.outputs.tags }}-lima
           labels: ${{ steps.metadata.outputs.labels }}
           ssh: |
             default=${{ env.SSH_AUTH_SOCK }}
       - 
         name: Build and push TYROL
         uses: docker/build-push-action@v3 
         with: 
           context: .
           file: Dockerfile
           push: true
           build-args: ENV_VARIABLE=tyrol
           tags: ${{ steps.metadata.outputs.tags }}-tyrol
           labels: ${{ steps.metadata.outputs.labels }}
           ssh: |
             default=${{ env.SSH_AUTH_SOCK }}
       - 
         name: Build and push PROD
         uses: docker/build-push-action@v3 
         with: 
           context: .
           file: Dockerfile
           push: true
           build-args: ENV_VARIABLE=prod
           tags: ${{ steps.metadata.outputs.tags }}-prod
           labels: ${{ steps.metadata.outputs.labels }}
           ssh: |
             default=${{ env.SSH_AUTH_SOCK }}


